version: '3.4'

services:
  weatherapi:
    image: weatherapi
    build:
      context: .
      dockerfile: ./src/Weather.API/Dockerfile
    ports:
      - "5072:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: weatherapi
    depends_on:
      - database

  weatherweb:
    image: weatherweb
    build:
      context: .
      dockerfile: ./src/Weather.Web/Dockerfile
    ports:
      - "4200:80"
    container_name: weatherweb
    depends_on:
      - weatherapi

  database:
    build: ./src/data
    environment:
      SA_PASSWORD: "Testando@123"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
        - "1433:1433"
    container_name: database
    hostname: database

volumes:
  mssqldata:

networks:
  semear:
    name: squadra-network
